import { ListingsGrid } from "@/components/marketplace/listings-grid"
import type { Listing } from "@/lib/types"

// Demo data
const demoListings: Listing[] = [
  {
    id: "1",
    user_id: "user1",
    title: "AI-Powered Content Generator",
    description: "Revolutionary AI tool that creates high-quality content for blogs, social media, and marketing.",
    price: 299,
    listing_type: "digital",
    category_id: "tech",
    images: ["/ai-marketing-dashboard.jpg"],
    is_verified: true,
    is_tokenized: true,
    token_id: null,
    contract_address: null,
    metadata: {},
    view_count: 1250,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    user_id: "user2",
    title: "Sustainable Fashion Collection",
    description: "Eco-friendly clothing line made from recycled materials. Perfect for conscious consumers.",
    price: 89,
    listing_type: "physical",
    category_id: "art",
    images: ["/sustainable-fashion-collection.jpg"],
    is_verified: true,
    is_tokenized: false,
    token_id: null,
    contract_address: null,
    metadata: {},
    view_count: 890,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    user_id: "user3",
    title: "Mobile App UI Kit",
    description: "Complete UI kit with 200+ components for building beautiful mobile applications.",
    price: 149,
    listing_type: "digital",
    category_id: "design",
    images: ["/mobile-app-ui-kit.jpg"],
    is_verified: true,
    is_tokenized: false,
    token_id: null,
    contract_address: null,
    metadata: {},
    view_count: 2100,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    user_id: "user4",
    title: "Handcrafted Wooden Furniture",
    description: "Custom-made wooden furniture pieces crafted by skilled artisans using sustainable wood.",
    price: 599,
    listing_type: "physical",
    category_id: "physical",
    images: ["/handcrafted-wooden-furniture.jpg"],
    is_verified: true,
    is_tokenized: false,
    token_id: null,
    contract_address: null,
    metadata: {},
    view_count: 450,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    user_id: "user5",
    title: "Freelance Consulting Services",
    description: "Expert business consulting for startups and small businesses. Strategy and growth planning.",
    price: 150,
    listing_type: "digital",
    category_id: "services",
    images: ["/business-consulting-meeting.jpg"],
    is_verified: true,
    is_tokenized: false,
    token_id: null,
    contract_address: null,
    metadata: {},
    view_count: 780,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    user_id: "user6",
    title: "Smart Home Automation System",
    description: "Complete IoT solution for automating your home. Easy setup and smartphone control.",
    price: 399,
    listing_type: "physical",
    category_id: "technology",
    images: ["/smart-home-automation.jpg"],
    is_verified: true,
    is_tokenized: true,
    token_id: null,
    contract_address: null,
    metadata: {},
    view_count: 1560,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export default function BuildersMarketplacePage() {
  return (
    <ListingsGrid
      title="Builder Marketplace"
      description="Discover innovative ideas, products, and services from verified builders worldwide."
      listings={demoListings}
    />
  )
}
